---
title: "ASJC Transformation from Scopus Journal data"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)
```

```{r}
library(tidyverse)
```

In tidy data, the following rules apply

- Each variable must have its own column.
- Each observation must have its own row.
- Each value must have its own cell.

<https://r4ds.had.co.nz/tidy-data.html>

### Get Scopus Journal list

```{r}
u <- "https://www.elsevier.com/__data/assets/excel_doc/0015/91122/ext_list_october_2019.xlsx"
download.file(u, "data/ext_list_october_2019.xlsx")
```

### Tidy Journal Classifications per Journal 

```{r}
scopus <- readxl::read_xlsx("data/ext_list_october_2019.xlsx")
scopus_jns <- scopus %>% 
  select(1:4, ajcs_all = `All Science Journal Classification Codes (ASJC)`) %>%
  # subject category one per row
  mutate(ajcs = strsplit(ajcs_all, "; ", fixed=TRUE)) %>%
  unnest(ajcs) %>%
  mutate(ajcs = gsub(";", "", ajcs)) %>%
  # issn type 
  gather(key = "issn_type", value = "issn", `Print-ISSN`, `E-ISSN`) %>%
  filter(!is.na(issn)) %>%
  # tidy issn
  mutate(issn = paste(substr(issn, 1, 4), substr(issn, 5,8), sep = "-"))
head(scopus_jns)

```

### Mapping AJSC Codes to Classification

```{r}
ajcs_data <- readxl::read_xlsx("data/ext_list_october_2019.xlsx", 
                                  sheet = "ASJC classification codes") 

ajcs_top <-  ajcs_data %>%
  select(top_code = code, top_level = `Description...5`, super_group = Supergroup) %>%
  mutate(top_code = gsub("\\*", "", top_code)) %>%
  mutate(top_code = gsub("00", "", top_code)) 
ajcs_all <- ajcs_data %>%
  select(code = Code, description = `Description...2`) %>%
  mutate(top_code = substr(code, 1,2)) %>%
  mutate(code = as.character(code)) %>%
  filter(!is.na(code)) %>%
  inner_join(ajcs_top, by = "top_code")
ajcs_all
# backup
write_csv(ajcs_all, "data/ajsc_hierarchy.csv")
```

### Merge with journal-level data

```{r}
scopus_tidy <- scopus_jns %>%
  inner_join(ajcs_all, by = c("ajcs" = "code")) %>%
  # rename
  select(scopus_id = 1, 
         journal_title = 2,
         issn_type, issn,
         ajcs, description,
         top_code, top_level, super_group
         )
head(scopus_tidy)
# backup 
write_csv(scopus_tidy, "data/scopus_asjc_tidy.csv")
```

